//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StaticTexts", typeof(StaticTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقدیرنامه های.
        /// </summary>
        public static string Acknowledgment {
            get {
                return ResourceManager.GetString("Acknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهران، سعادت آباد، چهارراه سرو، ابتدای سرو غربی ، پلاک 76، واحد 13 و 14.
        /// </summary>
        public static string AddressContent {
            get {
                return ResourceManager.GetString("AddressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی حقوق این وب سایت متعلق به شرکت آریا کابل فدک می باشد. طراحی و توسعه توسط.
        /// </summary>
        public static string AllRight {
            get {
                return ResourceManager.GetString("AllRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه های اخبار.
        /// </summary>
        public static string blogCatTitle {
            get {
                return ResourceManager.GetString("blogCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر مرکزی.
        /// </summary>
        public static string CenteralOffice {
            get {
                return ResourceManager.GetString("CenteralOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گواهینامه های.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت آریا کابل فدک.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فدک.
        /// </summary>
        public static string CompanyNameSmall {
            get {
                return ResourceManager.GetString("CompanyNameSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با ما در تماس باشید.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زاوش.
        /// </summary>
        public static string DevelopBy {
            get {
                return ResourceManager.GetString("DevelopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجهیزات.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نام و پیغام خود را وارد نمایید.
        /// </summary>
        public static string ErrorNameMessage {
            get {
                return ResourceManager.GetString("ErrorNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string FormEmail {
            get {
                return ResourceManager.GetString("FormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام.
        /// </summary>
        public static string FormMessage {
            get {
                return ResourceManager.GetString("FormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن تماس.
        /// </summary>
        public static string FormPhone {
            get {
                return ResourceManager.GetString("FormPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل خود را وارد نمایید.
        /// </summary>
        public static string InsertEmail {
            get {
                return ResourceManager.GetString("InsertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارنده گواهینامه ISO 9001:2008.
        /// </summary>
        public static string IsoText {
            get {
                return ResourceManager.GetString("IsoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین اخبار.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی سریع.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان.
        /// </summary>
        public static string MenuCustomer {
            get {
                return ResourceManager.GetString("MenuCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گالری.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات.
        /// </summary>
        public static string MenuProduct {
            get {
                return ResourceManager.GetString("MenuProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام در خبر نامه.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر گواهینامه ها.
        /// </summary>
        public static string OtherCer {
            get {
                return ResourceManager.GetString("OtherCer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر محصولات.
        /// </summary>
        public static string OtherProducts {
            get {
                return ResourceManager.GetString("OtherProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات محصول.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست محصولات، مشتریان و خدمات شرکت آریا کابل فدک به شرح زیر می باشد.
        /// </summary>
        public static string ProListSummery {
            get {
                return ResourceManager.GetString("ProListSummery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات بیشتر.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات مشابه.
        /// </summary>
        public static string RelatedProduct {
            get {
                return ResourceManager.GetString("RelatedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        public static string RouteParam {
            get {
                return ResourceManager.GetString("RouteParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما را در شبکه های اجتماعی دنبال نمایید.
        /// </summary>
        public static string SocialFollow {
            get {
                return ResourceManager.GetString("SocialFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شما با موفقیت ثبت گردید.
        /// </summary>
        public static string SubmitSuccess {
            get {
                return ResourceManager.GetString("SubmitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چطور میتوان با این شرکت وارد تجارت شد؟.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما میتوانید محصولات خریداری شده را از انبارهای شرکت آریاکابل در کشورهای عمان، ترکیه و آلمان تحویل بگیرید؛
        ///در واقع شما با یک شرکت ترک، عمانی یا آلمانی وارد معامله میشوید و محصولات مارا از طریق یک شرکت ترک، عمانی یا آلمانی تحویل میگیرید.
        ///
        ///بدین ترتیب مشتریان میتوانند تشریفات مالی و حمل و نقل را با بانک ها و شرکت‌های حمل و نقل کشورهای فوق انجام دهند.
        /// </summary>
        public static string TradeText {
            get {
                return ResourceManager.GetString("TradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلایل انتخاب آریا کابل فدک.
        /// </summary>
        public static string WhyUs {
            get {
                return ResourceManager.GetString("WhyUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات کاری.
        /// </summary>
        public static string WorkHour {
            get {
                return ResourceManager.GetString("WorkHour", resourceCulture);
            }
        }
    }
}
