//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fadak.Models
{
    using Fadak.Models.MetadataClasses;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(BlogsMetadata))]
    public partial class Blogs
    {
        public int Id { get; set; }
        public int fk_BlogCategoryId { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public string ImageUrl { get; set; }
        public int VisitNumber { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Title_En { get; set; }
        public string Detail_En { get; set; }
        public string Summery { get; set; }
        public string Summery_En { get; set; }
    
        public virtual BlogCategories BlogCategories { get; set; }
    }
}
