//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fadak.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FadakDBEntities : DbContext
    {
        public FadakDBEntities()
            : base("name=FadakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GalleryImages> GalleryImages { get; set; }
        public virtual DbSet<BlogCategories> BlogCategories { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<ProductImages> ProductImages { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<TextItems> TextItems { get; set; }
        public virtual DbSet<TextTypes> TextTypes { get; set; }
        public virtual DbSet<ContactForm> ContactForm { get; set; }
        public virtual DbSet<Newsletters> Newsletters { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<HeaderImages> HeaderImages { get; set; }
    }
}
