//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fadak.Models
{
    using Fadak.Models.MetadataClasses;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(SlidersMetadata))]
    public partial class Sliders
    {
        public int Id { get; set; }
        public string BigTitle { get; set; }
        public string BigTitle_En { get; set; }
        public string SmallTitle { get; set; }
        public string SmallTitle_En { get; set; }
        public string FirstLinkText { get; set; }
        public string FirstLinkText_En { get; set; }
        public string FirsLinkAddress { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
